apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: mongodb
  labels:
  {{- include "movies.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
    app: mongodb
spec:
  gateways:
  - mesh
  hosts:
  - mongodb.{{ .Release.Namespace }}.svc.cluster.local
  http:
  - route:
    - destination:
        host: mongodb.{{ .Release.Namespace }}.svc.cluster.local
        subset: stable

---

apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: mongodb
  labels:
  {{- include "movies.labels" . | nindent 4 }}
spec:
  host: mongodb.{{ .Release.Namespace }}.svc.cluster.local  
  subsets:
  - name: stable    
    labels:
      app: mongodb
      app.kubernetes.io/instance: {{ .Release.Name }}