apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: catalog
  labels:
  {{- include "movies.labels" . | nindent 4 }}
spec:
  gateways:
  - mesh
  hosts:
  - catalog.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - match:
      - gateways:
          - mesh
        port: 8080
      name: mesh-to-mesh
      route:
        - destination:
            host: catalog.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8080
            subset: stable
          weight: 100
      timeout: 60s

---

apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: catalog
  labels:
  {{- include "movies.labels" . | nindent 4 }}
spec:
  host: catalog.{{ .Release.Namespace }}.svc.cluster.local  
  subsets:
  - name: stable    
    labels:
      app.kubernetes.io/name: catalog
      app.kubernetes.io/instance: {{ .Release.Name }}